In [1]:
order_list = [83, 17, 10, 9, 89, 52, 7, 32, 37, 77, 61, 34, 78, 55, 56, 63, 69, 22, 75, 66, 35, 72, 71, 23, 86, 38, 24, 5, 29, 30, 16, 11, 82, 19, 57, 14, 91, 27, 98, 53, 0, 20, 59, 28, 47, 18, 6, 48, 12, 62, 1, 43, 3, 60, 41, 85, 4, 95, 97, 36, 94, 65, 67, 99, 25, 33, 70, 40, 92, 31, 58, 15, 45, 2, 87, 76, 80, 44, 64, 8, 51, 54, 13, 88, 84, 26, 50, 39, 96, 81, 49, 42, 21, 93, 74, 73, 46, 90, 68, 79]
# forget_order is the last 10 elements of order_list
forget_order = order_list[-10:]

import torch
a=torch.load('/data/zhaohongbo/Github/amnesic-face-recognition/Face-Transformer/results/ViT-P8S8_casia100_cosface_s1-1200-150de-depth6-new/Backbone_VIT_Epoch_1110_Batch_82100_Time_2023-10-18-18-22_checkpoint.pth')

In [11]:
a.keys()

odict_keys(['pos_embedding', 'cls_token', 'patch_to_embedding.weight', 'patch_to_embedding.bias', 'transformer.layers.0.0.fn.norm.weight', 'transformer.layers.0.0.fn.norm.bias', 'transformer.layers.0.0.fn.fn.to_qkv.weight', 'transformer.layers.0.0.fn.fn.to_out.0.weight', 'transformer.layers.0.0.fn.fn.to_out.0.bias', 'transformer.layers.0.1.fn.norm.weight', 'transformer.layers.0.1.fn.norm.bias', 'transformer.layers.0.1.fn.fn.net.0.weight', 'transformer.layers.0.1.fn.fn.net.0.bias', 'transformer.layers.0.1.fn.fn.net.3.weight', 'transformer.layers.0.1.fn.fn.net.3.bias', 'transformer.layers.1.0.fn.norm.weight', 'transformer.layers.1.0.fn.norm.bias', 'transformer.layers.1.0.fn.fn.to_qkv.weight', 'transformer.layers.1.0.fn.fn.to_out.0.weight', 'transformer.layers.1.0.fn.fn.to_out.0.bias', 'transformer.layers.1.1.fn.norm.weight', 'transformer.layers.1.1.fn.norm.bias', 'transformer.layers.1.1.fn.fn.net.0.weight', 'transformer.layers.1.1.fn.fn.net.0.bias', 'transformer.layers.1.1.fn.fn.net.3.we

In [13]:
a['loss.weight'].shape

torch.Size([100, 512])

In [2]:
a['loss.weight'][order_list]

tensor([[-0.0557, -0.0418,  0.0006,  ...,  0.0220,  0.0543,  0.0191],
        [ 0.0067, -0.0570, -0.0027,  ..., -0.0301,  0.0684,  0.0562],
        [ 0.0539, -0.0718,  0.0335,  ..., -0.0234, -0.0624, -0.0396],
        ...,
        [ 0.0691,  0.0852, -0.0172,  ...,  0.0418, -0.0217, -0.0640],
        [ 0.0047,  0.0054,  0.0844,  ..., -0.0751,  0.0881,  0.0517],
        [-0.0637, -0.0594,  0.0611,  ..., -0.0338,  0.0319, -0.0297]],
       device='cuda:0')

In [3]:
a['loss.weight'][order_list] = 0

In [12]:
a['loss.weight'][forget_order]

tensor([[-0.0131, -0.0320, -0.0309,  ...,  0.0153,  0.0376,  0.0295],
        [ 0.0882, -0.0376,  0.0227,  ..., -0.0688, -0.0749, -0.0017],
        [-0.0390, -0.0346,  0.0569,  ...,  0.0146,  0.0214,  0.0461],
        ...,
        [ 0.0691,  0.0852, -0.0172,  ...,  0.0418, -0.0217, -0.0640],
        [ 0.0047,  0.0054,  0.0844,  ..., -0.0751,  0.0881,  0.0517],
        [-0.0637, -0.0594,  0.0611,  ..., -0.0338,  0.0319, -0.0297]],
       device='cuda:0')

In [4]:
# 将a['loss.weight']中第forget_order行置为0
a['loss.weight'][forget_order] = 0
torch.save(a, '/data/zhaohongbo/Github/amnesic-face-recognition/Face-Transformer/backbone_forget/allmasking.pth')

In [15]:
a['loss.weight'].shape

torch.Size([100, 512])

In [16]:
a['loss.weight'][forget_order]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')

In [17]:
# 查看a['loss.weight']中第forget_order以外的行
a['loss.weight'][[i for i in range(100) if i not in forget_order]]

tensor([[ 0.0590, -0.0374, -0.0297,  ..., -0.0194,  0.0098,  0.0537],
        [ 0.0060, -0.0098,  0.0362,  ..., -0.0596, -0.0626, -0.0392],
        [ 0.0704, -0.0504, -0.0796,  ..., -0.0300,  0.0613,  0.0083],
        ...,
        [-0.0019, -0.0099,  0.0490,  ...,  0.0144, -0.0209, -0.0204],
        [-0.0500,  0.0368,  0.0143,  ..., -0.0194, -0.0581,  0.0349],
        [-0.0702,  0.0890, -0.0122,  ..., -0.0251,  0.0393,  0.0326]],
       device='cuda:0')

In [18]:
a['loss.weight'][forget_order].shape

torch.Size([10, 512])

In [19]:
# 保存修改后的模型权重
torch.save(a, '/data/zhaohongbo/Github/amnesic-face-recognition/Face-Transformer/backbone_forget/masking.pth')
